packages:
  - frontend/apps/*
  - frontend/libs/*

catalog:
  typescript: ^5.9.2
  "@types/bun": ^1.2.20
  "@types/node": ^24.9.1

catalogs:
  tailwindcss:
    tailwindcss: ^4.1.14
    "@tailwindcss/vite": ^4.1.14
    tailwind-scrollbar: ^4.0.2
  i18n:
    "@lingui/vite-plugin": ^5.4.1
    "@lingui/core": ^5.4.1
    "@lingui/detect-locale": ^5.4.1
    "@lingui/react": ^5.4.1
    "@lingui/cli": ^5.4.1
    "@lingui/conf": ^5.5.1
    vite-plugin-babel-macros: ^1.0.6
    eslint-plugin-lingui: ^0.11.0
    "@lingui/babel-plugin-lingui-macro": ^5.5.1
  react:
    react: ^19.2.0
    react-dom: ^19.2.0
    "@types/react": ^19.2.2
    "@types/react-dom": ^19.2.1
  tauri:
    "@tauri-apps/api": ^2.8.0
    "@tauri-apps/plugin-autostart": ^2.5.0
    "@tauri-apps/plugin-clipboard-manager": ^2.3.0
    "@tauri-apps/plugin-http": ^2.5.2
    "@tauri-apps/plugin-log": ^2.7.0
    "@tauri-apps/plugin-notification": ^2.3.1
    "@tauri-apps/plugin-os": ^2.3.1
    "@tauri-apps/plugin-shell": ^2.3.1
    "@tauri-apps/cli": ^2.8.4
  vite:
    vite: ^7.1.9
    vite-tsconfig-paths: ^5.1.4
    "@vitejs/plugin-legacy": ^7.2.1
    "@vitejs/plugin-react": ^5.0.4
  eslint:
    eslint: ^9.20.0
    "@eslint/js": ^9.20.0
    "@stylistic/eslint-plugin": ^4.2.0
    typescript-eslint: ^8.23.0
    eslint-plugin-react: ^7.37.4
    eslint-plugin-simple-import-sort: ^12.1.1
    eslint-plugin-unused-imports: ^4.1.4
  jotai:
    jotai: ^2.15.0
    jotai-devtools: ^0.13.0
    immer: ^10.1.1
    jotai-immer: ^0.4.1
  tanstack:
    "@tanstack/react-query": ^5.90.2
    "@tanstack/react-query-persist-client": ^5.90.2
    "@tanstack/react-router": ^1.132.47
    "@tanstack/react-router-devtools": ^1.132.51
    "@tanstack/eslint-plugin-query": ^5.91.0
    "@tanstack/router-plugin": ^1.132.51
    "@tanstack/react-table": ^8.21.3
  shadcn:
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    lucide-react: ^0.546.0
    tailwind-merge: ^3.3.1
    tw-animate-css: ^1.4.0
    "@radix-ui/react-slot": ^1.2.3
    "@radix-ui/react-navigation-menu": ^1.2.14
    "@radix-ui/react-avatar": ^1.1.10
    "@radix-ui/react-dialog": ^1.1.15
    "@radix-ui/react-dropdown-menu": ^2.1.16
    "@radix-ui/react-label": ^2.1.7
    "@radix-ui/react-select": ^2.2.6
    "@radix-ui/react-separator": ^1.1.7
    "@radix-ui/react-switch": ^1.2.6
    "@radix-ui/react-toggle": ^1.1.10
    "@radix-ui/react-toggle-group": ^1.1.11
    "@radix-ui/react-tooltip": ^1.2.8
    "@radix-ui/react-alert-dialog": ^1.1.15
    "@radix-ui/react-tabs": ^1.1.13
    "@radix-ui/react-checkbox": ^1.3.3
    sonner: ^2.0.7
  icon:
    "@mdi/js": ^7.4.47
    "@mdi/react": ^1.6.1
    "@tabler/icons-react": ^3.35.0
  zod:
    zod: ^4.1.12
