name: Test Build Scripts
run-name: "Test Build Scripts: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.event_name }}"
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  pytest:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.9.2
          python-version: 3.12
          enable-cache: true
          restore-cache: true
          save-cache: true
          prune-cache: true
      - name: Install python dependencies
        run: uv sync
      - name: Run tests
        run: uv run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=lavascope_cli_lib > pytest-coverage.txt
      - name: Pytest coverage comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: MishaKav/pytest-coverage-comment@v1
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          title: "Build Scripts Coverage Report"
          junitxml-title: "Build Scripts Test Results"
