name: Test Build
run-name: "Test Build: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.event_name }}"
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-desktop-build:
    if: ${{ !startsWith(github.head_ref, 'release/')}}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        build: [linux, macos-x86_64, macos-arm, windows]
        include:
          - build: macos-arm
            os: macos-latest
            args: "--config src-tauri/build-config/tauri.macos.conf.json --target aarch64-apple-darwin"
          - build: macos-x86_64
            os: macos-latest
            args: "--config src-tauri/build-config/tauri.macos.conf.json --target x86_64-apple-darwin"
          - build: linux
            os: ubuntu-22.04
            args: ""
          - build: windows
            os: "windows-latest"
            args: "--config src-tauri/build-config/tauri.windows.conf.json"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies (ubuntu only)
        if: matrix.build == 'linux'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.os == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"
      - name: Install frontend dependencies
        run: bun install --frozen-lockfile
      - name: Build Tauri app
        id: tauri-build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tauriScript: bun run tauri
          args: ${{ matrix.args }}
      - name: Actifact list
        env:
          RELEASE_ACTIFACTS: ${{steps.tauri-build.outputs.artifactPaths}}
        uses: actions/github-script@v7
        with:
          script: |
            const artifactArray = JSON.parse(process.env.RELEASE_ACTIFACTS);
            for (const artifact of artifactArray) {
              console.log(`Artifact: ${artifact}`);
            }
  test-android-build:
    if: ${{ !startsWith(github.head_ref, 'release/')}}
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    environment: Release
    env:
      JAVA_DISTRIBUTION: 'adopt'
      JAVA_VERSION: 17
      NDK_VERSION: 27.1.12297006
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{env.JAVA_DISTRIBUTION}}
          java-version: ${{env.JAVA_VERSION}}
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install NDK
        run: |
          sdkmanager "ndk;$NDK_VERSION"
          echo "NDK_HOME=$ANDROID_HOME/ndk/$NDK_VERSION" >> $GITHUB_ENV
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"
      - name: Install frontend dependencies
        run: bun install --frozen-lockfile
      - name: Setup Android signing
        run: |
          base64 -d <<< ${{secrets.ANDROID_KEY_BASE64}} > $RUNNER_TEMP/keystore.jks
          echo "keyAlias=${{secrets.ANDROID_KEY_ALIAS}}" > src-tauri/gen/android/keystore.properties
          echo "password=${{secrets.ANDROID_KEY_PASSWORD}}" >> src-tauri/gen/android/keystore.properties
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> src-tauri/gen/android/keystore.properties
      - name: Build Android bundle
        run: |
          bun run tauri android build -v --config src-tauri/build-config/tauri.android.conf.json
      - name: Build Android APK per abi
        run: |
          bun run tauri android build -v --config src-tauri/build-config/tauri.android.conf.json --apk --split-per-abi
